In [132]:
import numpy as np
import pandas as pd
pd.set_option("display.precision", 5)
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
%config InlineBackend.figure_format = 'retina'
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

In [133]:
skindata = pd.read_csv('E:/Data_science/Skin_NonSkin.csv')

In [143]:
skindata.head()

Blue  Green  Red  Skin
0    73     84  122     1
1    72     83  121     1
2    70     81  119     1
3    70     81  119     1
4    69     80  118     1

In [144]:
skindata.columns = ['Blue', 'Green','Red' , 
                        'Skin'] 

In [145]:
skindata.head()

Blue  Green  Red  Skin
0    73     84  122     1
1    72     83  121     1
2    70     81  119     1
3    70     81  119     1
4    69     80  118     1

In [146]:
Skindata_new= skindata.iloc[:,0:3]

In [147]:
Skindata_new.head()

Blue  Green  Red
0    73     84  122
1    72     83  121
2    70     81  119
3    70     81  119
4    69     80  118

In [141]:
Skin_new = pd.get_dummies(skindata['Skin'])




In [148]:
Skin_new

1  2
0       1  0
1       1  0
2       1  0
3       1  0
4       1  0
...    .. ..
245051  0  1
245052  0  1
245053  0  1
245054  0  1
245055  0  1

[245056 rows x 2 columns]

In [149]:
skindata=pd.concat([skindata,Skin_new],axis=1)

In [162]:
skindata.drop(['Skin'],axis=1)


Blue  Green  Red  1  2
0         73     84  122  1  0
1         72     83  121  1  0
2         70     81  119  1  0
3         70     81  119  1  0
4         69     80  118  1  0
...      ...    ...  ... .. ..
245051   163    162  112  0  1
245052   163    162  112  0  1
245053   163    162  112  0  1
245054   163    162  112  0  1
245055   255    255  255  0  1

[245056 rows x 5 columns]

In [163]:
skindata.rename(columns = {'2':'Skin'}, inplace = True)

In [164]:
skindata

Blue  Green  Red  Skin  1  2
0         73     84  122     1  1  0
1         72     83  121     1  1  0
2         70     81  119     1  1  0
3         70     81  119     1  1  0
4         69     80  118     1  1  0
...      ...    ...  ...   ... .. ..
245051   163    162  112     2  0  1
245052   163    162  112     2  0  1
245053   163    162  112     2  0  1
245054   163    162  112     2  0  1
245055   255    255  255     2  0  1

[245056 rows x 6 columns]

In [165]:
from sklearn.cluster import KMeans

In [166]:
kmeans = KMeans(n_clusters=2)

In [167]:
kmeans.fit(Skindata_new)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [168]:
kmeans.cluster_centers_

array([[157.74289767, 165.51849544, 157.47397345],
       [ 53.14157142,  59.84887989,  47.68830253]])

In [169]:
kmeans.labels_

array([1, 1, 1, ..., 0, 0, 0])

In [170]:
pred=pd.DataFrame(kmeans.labels_)

In [175]:
from sklearn.metrics import confusion_matrix,classification_report

In [176]:
confusion_matrix(Skin_new[1],pred)

array([[126387,  67811],
       [ 42140,   8718]], dtype=int64)

In [177]:
print(classification_report(Skin_new[1],pred))

              precision    recall  f1-score   support

           0       0.75      0.65      0.70    194198
           1       0.11      0.17      0.14     50858

    accuracy                           0.55    245056
   macro avg       0.43      0.41      0.42    245056
weighted avg       0.62      0.55      0.58    245056

